os: Visual Studio 2015

version: 0.1.{build}

install:
- ps: .\Source\Scripts\CI.InstallSystemPrereqs.ps1

build_script:
- ps: .\CI Build

deploy_script:
- ps: .\CI Deploy FunctionalTest

test: off

cache:
  - .\psake.4.4.2
  - .\Source\packages -> .\Source\ExampleApp.Web\packages.config
  - C:\Users\appveyor\AppData\Roaming\Windows Azure Powershell\AzureDataCollectionProfile.json

on_failure:
  - ps: if (Test-Path .\Artifacts\Screenshots) { Get-ChildItem .\Artifacts\Screenshots | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name } }