os: Visual Studio 2015

version: 0.1.{build}

build_script:
  - ps: .\Source\Scripts\CI.InstallSystemPrereqs.ps1;.\CI Build

artifacts:
  - name: Logs
    path: Artifacts\Logs

deploy_script:
  - ps: .\CI "Deploy,FunctionalTest"

test: off

cache:
  - .\Source\packages -> .\Source\ExampleApp\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified