os: Visual Studio 2015

install:
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

version: 0.1.{build}

build_script:
  - ps: .\Source\Scripts\CI.InstallSystemPrereqs.ps1;.\CI Build

artifacts:
  - name: Logs
    path: Artifacts\Logs

deploy_script:
  - ps: .\CI "Deploy,FunctionalTest"

test: off

cache:
  - .\Source\packages -> .\Source\ExampleApp.Web\packages.config
  - C:\Users\appveyor\AppData\Roaming\Windows Azure Powershell\AzureDataCollectionProfile.json